beamerpis:
  hosts:
    bpi1:
      ansible_host: 192.168.1.102
    bpi2:
      ansible_host: 10.13.66.32
    bpi3:
      ansible_host: 10.13.66.33
    bpi4:
      ansible_host: 10.13.66.34
    bpi5:
      ansible_host: 10.13.66.35
  vars:
    ansible_user: pi
    kiosk_controller: http://kiosk.mgmt.nlpt.network
    ntp_server: kiosk.mgmt.nlpt.network
